name: deploy to production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: build
        uses: actions/setup-node@v1
        with:
          node-version: "20.x"
      - run: npm install && npm run build
        env:
          ASSET_PREFIX: "/staging"
          NEXT_PUBLIC_BASE_URL: "https://graces-scalp.jp/staging/"
      - name: ssh key generate
        run: echo "$SSH_PRIVATE_KEY" > key && chmod 600 key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: rsync deploy
        run: |
          ssh -i key -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 10022 okinawa2020@sv13174.xserver.jp 'rm -rf /home/okinawa2020/graces-scalp.jp/public_html/staging/*'
          rsync -auzrv --delete --exclude .htaccess -e "ssh -i key -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 10022" --delete ./out/* okinawa2020@sv13174.xserver.jp:/home/okinawa2020/graces-scalp.jp/public_html/staging/ --exclude .htaccess
